# Debug flags
set(CMAKE_C_FLAGS "-std=c99")
if(NOT APPLE)
  set(CMAKE_C_FLAGS_DEBUG             "-g -ggdb3")
  set(CMAKE_CXX_FLAGS_DEBUG           "-g -ggdb3")
  set(CMAKE_EXE_LINKER_FLAGS_DEBUG    "-ggdb3")
  set(CMAKE_MODULE_LINKER_FLAGS_DEBUG "-ggdb3")
  set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "-ggdb3")
  add_definitions(-D_GNU_SOURCE)
else(NOT APPLE)
  set(CMAKE_C_FLAGS_DEBUG             "-g -gdwarf-4")
  set(CMAKE_CXX_FLAGS_DEBUG           "-g -gdwarf-4")
  set(CMAKE_EXE_LINKER_FLAGS_DEBUG    "-gdwarf-4")
  set(CMAKE_MODULE_LINKER_FLAGS_DEBUG "-gdwarf-4")
  set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "-gdwarf-4")  
endif(NOT APPLE)
