.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH bzzc 1 "April 2016" Linux "User Commands"
.SH NAME
bzzc \- the Buzz compiler
.SH SYNOPSIS
\fBbzzc\fR [ \fB-v \fR]
     [ \fB-I \fIpath1:path2:...:pathN \fR]
     [ \fB-b \fIscript.bo \fR]
     [ \fB-d \fIscript.bdb \fR]
     [ \fB-a \fIscript.basm \fR]
     \fIscript.bzz
.SH DESCRIPTION
.P
\fBbzzc\fR compiles the given Buzz script \fIscript.bzz\fR and
produces two files: \fIscript.bo\fR, the compiled bytecode ready to be
executed by the Buzz Virtual Machine, and \fIscript.bdb\fR, a file
containing debugging information.  The file \fIscript.bo\fR must be
uploaded on the robot.  The file \fIscript.bdb\fR is located on the
machine used by the developer to debug/monitor the robots. Optionally,
\fBbzzc\fR can also create the Buzz assembly file. This occurs when
the option \fB-a\fR is specified.
.SH OPTIONS
.TP
\fB\-v|--version\fR
Shows version information
.TP
\fB\-I|--include \fIpath1:path2:...:pathN\fR
Append the given paths to \fBBUZZ_INCLUDE_PATH\fR
.TP
\fB\-b|--bytecode \fIscript.bo
Set explicitly the bytecode file name
.TP
\fB\-d|--debug \fIscript.bdb
Set explicitly the debug file name
.TP
\fB\-a|--asm \fIscript.basm
Set explicitly the assembly file name
.SH ENVIRONMENT
.TP
.B BUZZ_INCLUDE_PATH
A colon-separated list of paths in which include files are searched
for during compilation
.TP
.B BZZPARSE
The full path to the \fBbzzparse\fR(1) command.
.TP
.B BZZASM
The full path to the \fBbzzasm\fR(1) command.
.SH SEE ALSO
.BR bzzparse (1)
.BR bzzasm (1)
.BR bzzdeasm (1)
.BR bzzrun (1)
.SH MORE INFORMATION
Online documentation on the Buzz toolset:
.br
http://the.swarming.buzz/wiki/doku.php?id=buzz_toolset
.SH AUTHOR
Carlo Pinciroli <ilpincy@gmail.com>
