#!/usr/bin/env bash

#
# Stop after any error
#
set -e

#
# Check tools
#
command -v bzzparse >/dev/null 2>&1 || { echo >&2 "$0: error: can't find bzzparse"; exit 1; }
command -v bzzasm >/dev/null 2>&1 || { echo >&2 "$0: error: can't find bzzasm"; exit 1; }

#
# Check command line
#
if [ $# -ne 1 ]; then
    echo "Usage: $0 script.bzz"
    exit 1
fi

#
# File names
#
BZZ=$1
BASM=$(echo $BZZ | rev | cut -d. -f 2- | rev).basm
BO=$(echo $BZZ | rev | cut -d. -f 2- | rev).bo
BDBG=$(echo $BZZ | rev | cut -d. -f 2- | rev).bdbg

#
# Compilation
#
bzzparse $BZZ $BASM && bzzasm $BASM $BO $BDBG
